Repository CatsInTech/Rezume, pull requests merged in 2020-03, with the labels that each got.

#25 GitHub actions
  .github/workflows/greetings.yml
Labels: Good to Go!, easy, gssoc20

#30 Added Pull Request Template and Issue Template
  .github/ISSUE_TEMPLATE/bug_report_template.md
  .github/ISSUE_TEMPLATE/feature_request_template.md
  .github/pull_request_template.md
Labels: Good to Go!, beginner, gssoc20

#32 Updated nav to be semantically correct.
  src/components/Header/_NavLink.js
  src/styles/_header.scss
Labels: easy, gssoc20

#35 Used the value props in textarea
  src/components/Forms/_FormElement.js
Labels: Good to Go!, beginner, gssoc20

#38 Created ReadME with the info. about the project
  README.md
  ReadME.md
Labels: Good to Go!, gssoc20, medium

#36 Added the actions for autoassign and stale issue
  .github/auto_assign.yml
  .github/workflows/assign.yml
  .github/workflows/stale.yml
Labels: Good to Go!, gssoc20, medium
