Repository CatsInTech/Rezume, pull requests merged in 2022-03, with the labels that each got.

#84 Changing Occupation Position and making copyright year dynamic Fixes …
  src/components/Footer/Footer.js
Labels: has conflicts

#62 Update in App.js resolve #42
  src/components/App.js
Labels: has conflicts

#120 Added profile image to resolve issue #99
  src/components/App.js
  src/components/Forms/Forms.js
  src/components/Forms/_FormElement.js
  src/components/Main/Main.js
  src/components/Rezume/Rezume.js
  src/styles/_rezume.scss
Labels: GSSoC22, Level3

#123 Update the homepage URL.
  package.json
Labels: GSSoC22, Level0

#125 Updated Button to be a link.
  src/components/Header/Header.js
Labels: GSSoC22, Level1
